
@startuml
User -> SystemHomePage : Log In
activate User
activate SystemHomePage
activate UserHomePage
SystemHomePage -> UserHomePage  : onCreate()
UserHomePage -> UserHomePageController: onCreate
activate UserHomePageController
User -> UserHomePage : Click Manage Quote
UserHomePage -> UserHomePageController : Send Information
UserHomePageController -> ManageQuotePage : onClickCreate ()
activate ManageQuotePage
UserHomePageController -> ManageQuotePage : Display Field
ManageQuotePage -> ManageQuotePageController : onCreate()
activate ManageQuotePageController
ManageQuotePage --> User : Display Page
@enduml