@startuml

class PropertyInformation {
Company Name
Address
}

class BuildingInformation{
Buildings
Units
Rooms
Floors
Notes
Rack Location
}

class Cost {
Hours
Labor Fee
Product Cost
}

class Customer {

}

class Equipment {

}

class Information
class Quote
class InstallationCompany

class Employee {

}

class Cable
class Modem
class Routers
class WirelessAccessPoints

class ContactInformation {
    Name
    Phone Number
    Email Address
}

Customer "1" -- "1" InstallationCompany : Hires
PropertyInformation --|> Information
Quote "1" -- "1" Information : Displays
BuildingInformation --|> Information
InstallationCompany "1" -- "+" Information : Fills Out
InstallationCompany "1" -- "+" Equipment : Provides
InstallationCompany "1" -- "+" Employee : Hires
Quote "1" -- "1" Equipment : Displays
Quote "1" -- "1" Cost : Displays
Quote "1" -- "1" InstallationCompany : Gets
Quote "1" -- "1" Customer : Gets
Cost "1" -- "1" Information : Calculates
Cost "1" -- "+" Equipment : Calculates
Customer "1" -- "+" Information : Provides
Equipment <|-- Cable
Equipment <|-- Modem
Equipment <|-- Routers
Equipment <|-- WirelessAccessPoints

Customer "1" -- "1" ContactInformation : Has
Employee "1" -- "1" ContactInformation : Has


@enduml