@startuml
User -> ActivityBarPage : Call Log Off
activate User
activate ActivityBarPage
ActivityBarPage -> ActivityBarPageController : onCreate()
activate ActivityBarPageController
ActivityBarPageController -> LogOff : onCreate
activate LogOff
ActivityBarPageController -> LogOff : Display Fields
LogOff -> LogOff : Display Options
User -> LogOff : Yes
LogOff --> ActivityBarPageController : logOff(True)
deactivate LogOff
ActivityBarPageController -> SystemHomePage : onCreate()
activate SystemHomePage
deactivate ActivityBarPageController
@enduml