@startuml
Employee -> SystemHomePage : Log In
activate Employee
activate SystemHomePage
activate EmployeeHomePage
SystemHomePage -> EmployeeHomePage  : onCreate()
EmployeeHomePage -> EmployeeHomePageController: onCreate
activate EmployeeHomePageController
Employee -> EmployeeHomePage : Create New Quote
EmployeeHomePage -> EmployeeHomePageController : createNewQuote()
EmployeeHomePageController -> CreateQuotePage : On Create
activate CreateQuotePage
CreateQuotePage -> CreateQuotePageController : onCreate()
activate CreateQuotePageController
CreateQuotePage --> Employee : Empty Fields
Employee -> CreateQuotePage : Fill Out Fields
Employee -> CreateQuotePage : Submit New Quote
CreateQuotePage -> CreateQuotePageController : Send Information
CreateQuotePageController -> CreateQuotePageController : Validate
CreateQuotePageController -> Server : validate(True)
activate Server
Server --> CreateQuotePageController : quoteSave(True)
CreateQuotePageController --> CreateQuotePage : quoteSaved(True)
CreateQuotePage --> Employee : Display Quote Saved
@enduml