@startuml
User -> System : Log In
activate System
activate User
System --> User : Display Home Screen
User -> System : Customer List
System --> User : Customer Page
User -> System : Select Remove Customer
System --> User : Confirm Remove
User -> System : Denies Remove
System --> User : Customer List Page
@enduml