@startuml
User -> SystemHomePage : Log In
activate User
activate SystemHomePage
activate UserHomePage
SystemHomePage -> UserHomePage  : onCreate()
UserHomePage -> UserHomePageController: onCreate
activate UserHomePageController
User -> UserHomePage : Click Manage Quote
UserHomePage -> UserHomePageController : Send Information
UserHomePageController -> ManageQuotePage : onClickCreate ()
activate ManageQuotePage
UserHomePageController -> ManageQuotePage : Display Field
ManageQuotePage -> ManageQuotePageController : onCreate()
activate ManageQuotePageController
User -> ManageQuotePage : Select Quote
User -> ManageQuotePage : Edit Quote
ManageQuotePage -> ManageQuotePageController : Send Information
ManageQuotePageController -> EditQuotePage : onCreate()
activate EditQuotePage
EditQuotePage -> EditQuotePageController : onCreate()
activate EditQuotePageController
EditQuotePage -> EditQuotePageController : Send Information
EditQuotePageController -> EditQuotePageController : verify()
EditQuotePageController --> EditQuotePage : quoteDNE(True)
EditQuotePage --> User : Display: No Quote Exists
EditQuotePage --> ManageQuotePageController : reCreate()
ManageQuotePageController --> ManageQuotePage : reCreate()
ManageQuotePage --> User : Wait For User
@enduml